package cli

import (
	"crypto/rand"
	"crypto/rsa"
	"encoding/hex"
	"fmt"
	"net/url"
	"os"
	"strings"

	"github.com/urfave/cli/v2"

	"github.com/eugenioenko/autentico/pkg/key"
)

func RunInit(c *cli.Context) error {
	if _, err := os.Stat(".env"); err == nil {
		return fmt.Errorf(".env already exists. Delete it first if you want to reinitialize")
	}

	appURL := c.String("url")
	if appURL == "" {
		appURL = "http://localhost:9999"
	}
	// Normalize: remove trailing slash
	appURL = strings.TrimRight(appURL, "/")

	// Derive host components from the URL
	u, err := url.Parse(appURL)
	if err != nil {
		return fmt.Errorf("invalid --url: %w", err)
	}
	if u.Scheme == "" || u.Host == "" {
		return fmt.Errorf("--url must include scheme and host, e.g. http://localhost:9999")
	}

	dev := c.Bool("dev")

	// Generate cryptographic secrets
	accessSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate access token secret: %w", err)
	}
	refreshSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate refresh token secret: %w", err)
	}
	csrfSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate CSRF secret: %w", err)
	}

	// Generate RSA private key for token signing
	rsaKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return fmt.Errorf("failed to generate RSA key: %w", err)
	}
	privateKeyB64 := key.EncodeKeyToBase64(rsaKey)

	secureCookieValue := "true"
	cookieComment := "# Cookie security — requires HTTPS. Set to false only for local HTTP development."
	if dev {
		secureCookieValue = "false"
		cookieComment = "# Cookie security (development mode — HTTP only)\n# WARNING: do NOT use these settings in production; cookies will be sent over plaintext HTTP."
	}

	// Build .env content
	lines := []string{
		"# Autentico configuration — generated by 'autentico init'",
		"# Keep this file secret and do not commit it to version control.",
		"",
		"AUTENTICO_DB_FILE_PATH=./db/autentico.db",
		"",
		"# Application URL — used for OIDC issuer and redirect URIs",
		fmt.Sprintf("AUTENTICO_APP_URL=%s", appURL),
		"AUTENTICO_APP_OAUTH_PATH=/oauth2",
		"AUTENTICO_APP_ENABLE_CORS=true",
		"",
		"# Cryptographic secrets — keep these private",
		fmt.Sprintf("AUTENTICO_ACCESS_TOKEN_SECRET=%s", accessSecret),
		fmt.Sprintf("AUTENTICO_REFRESH_TOKEN_SECRET=%s", refreshSecret),
		fmt.Sprintf("AUTENTICO_CSRF_SECRET_KEY=%s", csrfSecret),
		"",
		"# RSA private key for JWT signing (base64-encoded PEM)",
		"# If unset, an ephemeral key is generated on each startup (tokens invalidated on restart).",
		fmt.Sprintf("AUTENTICO_PRIVATE_KEY=%s", privateKeyB64),
		"AUTENTICO_JWK_CERT_KEY_ID=autentico-key-1",
		"",
		cookieComment,
		fmt.Sprintf("AUTENTICO_CSRF_SECURE_COOKIE=%s", secureCookieValue),
		"AUTENTICO_REFRESH_TOKEN_COOKIE_NAME=autentico_refresh_token",
		fmt.Sprintf("AUTENTICO_REFRESH_TOKEN_SECURE=%s", secureCookieValue),
		"AUTENTICO_IDP_SESSION_COOKIE_NAME=autentico_idp_session",
		fmt.Sprintf("AUTENTICO_IDP_SESSION_SECURE=%s", secureCookieValue),
		"",
		"# Internal ports",
		"AUTENTICO_SWAGGER_PORT=8888",
	}

	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(".env", []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .env: %w", err)
	}

	fmt.Println(".env file created successfully.")
	fmt.Printf("  App URL:    %s\n", appURL)
	fmt.Printf("  Issuer:     %s/oauth2\n", appURL)
	fmt.Println("")
	if dev {
		fmt.Println("  NOTE: Generated in development mode (--dev).")
		fmt.Println("  Secure cookie flags are disabled for local HTTP use.")
		fmt.Println("  Re-run without --dev for a production configuration.")
		fmt.Println("")
	}
	fmt.Println("Next steps:")
	fmt.Println("  1. Run 'autentico start' to start the server")
	fmt.Println("  2. Open the admin UI and complete the onboarding to create your admin account")

	return nil
}

// randomHex generates n random bytes and returns them as a hex string.
func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
