package cli

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/joho/godotenv"
	"github.com/urfave/cli/v2"

	"github.com/eugenioenko/autentico/pkg/config"
	"github.com/eugenioenko/autentico/pkg/verifico"
)

func buildVerificoEnvContent(listenURL, secret string) string {
	lines := []string{
		"# Verifico worker configuration — generated by 'autentico verifico init'",
		"# This file must be present in the working directory when running 'autentico verifico start'.",
		"",
		"# Shared secret for authenticating requests from the Autentico master.",
		"# Must match AUTENTICO_VERIFICO_SECRET on the master.",
		fmt.Sprintf("AUTENTICO_VERIFICO_SECRET=%s", secret),
		"",
		"# Address this worker listens on.",
		fmt.Sprintf("AUTENTICO_VERIFICO_URL=%s", listenURL),
		"",
		"# Limit the number of OS threads (CPU cores) this worker uses.",
		"# 0 = use all available cores (default).",
		"# AUTENTICO_MAX_PROCS=0",
	}
	return strings.Join(lines, "\n") + "\n"
}

func RunVerificoInit(c *cli.Context) error {
	outputDir := c.String("output")
	envPath := filepath.Join(outputDir, ".env")
	if _, err := os.Stat(envPath); err == nil {
		return fmt.Errorf("%s already exists. Delete it first if you want to reinitialize", envPath)
	}

	listenURL := c.String("url")
	if listenURL == "" {
		listenURL = "http://0.0.0.0:5050"
	}
	listenURL = strings.TrimRight(listenURL, "/")

	u, err := url.Parse(listenURL)
	if err != nil {
		return fmt.Errorf("invalid --url: %w", err)
	}
	if u.Scheme == "" || u.Host == "" {
		return fmt.Errorf("--url must include scheme and host, e.g. http://0.0.0.0:5050")
	}

	secret := c.String("secret")
	if secret == "" {
		return fmt.Errorf("--secret is required; use the same shared secret across all workers and the master")
	}

	content := buildVerificoEnvContent(listenURL, secret)
	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .env: %w", err)
	}

	fmt.Println("Verifico worker .env created successfully.")
	fmt.Printf("  Listen URL: %s\n", listenURL)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Printf("  1. Add this worker to the master: AUTENTICO_VERIFICO_WORKERS=%s\n", u.Host)
	fmt.Println("  2. Enable verifico on the master: AUTENTICO_VERIFICO_ENABLED=true")
	fmt.Println("  3. Run 'autentico verifico start' to start this worker")

	return nil
}

func RunVerificoTest(c *cli.Context) error {
	config.InitBootstrap()
	bs := config.GetBootstrap()

	if !bs.VerificoEnabled {
		fmt.Println("Verifico is disabled.")
		fmt.Println("Set AUTENTICO_VERIFICO_ENABLED=true to enable it.")
		return nil
	}

	var workers []string
	for _, w := range strings.Split(bs.VerificoWorkers, ",") {
		w = strings.TrimSpace(w)
		if w != "" {
			workers = append(workers, w)
		}
	}

	if len(workers) == 0 {
		fmt.Println("Verifico is enabled but no workers are configured.")
		fmt.Println("Set AUTENTICO_VERIFICO_WORKERS to a comma-separated list of host:port addresses.")
		return nil
	}

	verifico.Init(verifico.Config{Enabled: true, Workers: workers, Secret: bs.VerificoSecret})

	fmt.Printf("Verifico is enabled with %d worker(s).\n", len(workers))
	fmt.Println()

	results := verifico.TestWorkers()
	healthy := 0
	for _, r := range results {
		if r.Reachable && r.SecretValid {
			healthy++
			fmt.Printf("  ✓ %s — reachable, secret ok (%s)\n", r.Address, r.Latency.Round(time.Millisecond))
		} else if r.Reachable {
			fmt.Printf("  ✗ %s — reachable, %s\n", r.Address, r.Error)
		} else {
			fmt.Printf("  ✗ %s — unreachable, %s\n", r.Address, r.Error)
		}
	}

	fmt.Println()
	fmt.Printf("Result: %d/%d workers healthy.\n", healthy, len(results))
	return nil
}

func RunVerificoStart(c *cli.Context) error {
	_ = godotenv.Load()

	secret := os.Getenv("AUTENTICO_VERIFICO_SECRET")
	if secret == "" {
		return fmt.Errorf("AUTENTICO_VERIFICO_SECRET is required; run 'autentico verifico init' to generate a .env")
	}

	port := c.String("port")
	if port == "" {
		if envURL := os.Getenv("AUTENTICO_VERIFICO_URL"); envURL != "" {
			if u, err := url.Parse(envURL); err == nil && u.Port() != "" {
				port = u.Port()
			}
		}
		if port == "" {
			port = "5050"
		}
	}

	maxProcs := config.GetEnvInt("AUTENTICO_MAX_PROCS", 0)
	if maxProcs > 0 {
		runtime.GOMAXPROCS(maxProcs)
		fmt.Printf("  GOMAXPROCS set to %d\n", maxProcs)
	}

	return verifico.RunWorkerServer(port, secret)
}
