/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get JWKS
         * @description Returns the JSON Web Key Set for verifying JWTs
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.JWKSResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/openid-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Well-Known Configuration
         * @description Returns the OpenID Connect Well-Known Configuration
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.WellKnownConfigResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorize a client
         * @description Handles the authorization request and displays the login page
         */
        get: {
            parameters: {
                query: {
                    /** @description Response type */
                    response_type: string;
                    /** @description Client ID */
                    client_id: string;
                    /** @description Redirect URI */
                    redirect_uri: string;
                    /** @description Scope */
                    scope?: string;
                    /** @description State */
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description HTML login page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Introspect a token
         * @description Validates and retrieves metadata about a token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Token introspection payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["introspect.IntrospectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["introspect.IntrospectResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in a user
         * @description Authenticates a user and generates an authorization code
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description Username */
                        username: string;
                        /** @description Password */
                        password: string;
                        /** @description Redirect URI */
                        redirect: string;
                        /** @description State */
                        state: string;
                    };
                };
            };
            responses: {
                /** @description Redirect to the provided URI with code and state */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out a user
         * @description Terminates the user's session
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer access token */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session terminated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all clients
         * @description Lists all registered clients (admin only)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["client.ClientInfoResponse"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Register a new OAuth2 client
         * @description Registers a new OAuth2/OIDC client (admin only)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Client registration request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["client.ClientCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["client.ClientResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/register/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get client information
         * @description Retrieves information about a registered client (admin only)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Client ID */
                    client_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["client.ClientInfoResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
            };
        };
        /**
         * Update client information
         * @description Updates a registered client (admin only)
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Client ID */
                    client_id: string;
                };
                cookie?: never;
            };
            /** @description Client update request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["client.ClientUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["client.ClientInfoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Deactivate a client
         * @description Deactivates (soft deletes) a registered client (admin only)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Client ID */
                    client_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.AuthErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a token
         * @description Revokes an access or refresh token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description Token to revoke */
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Token revoked successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token endpoint
         * @description Exchanges authorization code or credentials for tokens
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description Grant type */
                        grant_type: string;
                        /** @description Authorization code */
                        code?: string;
                        /** @description Redirect URI */
                        redirect_uri?: string;
                        /** @description Client ID */
                        client_id?: string;
                        /** @description Username */
                        username?: string;
                        /** @description Password */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["token.TokenResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user information
         * @description Retrieves user information based on the access token
         */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Bearer access token */
                    Authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new user
         * @description Registers a new user in the system
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User creation payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["user.UserCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user.UserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "client.ClientCreateRequest": {
            client_name?: string;
            client_type?: string;
            grant_types?: string[];
            redirect_uris?: string[];
            response_types?: string[];
            scopes?: string;
            token_endpoint_auth_method?: string;
        };
        "client.ClientInfoResponse": {
            client_id?: string;
            client_name?: string;
            client_type?: string;
            grant_types?: string[];
            is_active?: boolean;
            redirect_uris?: string[];
            response_types?: string[];
            scopes?: string;
            token_endpoint_auth_method?: string;
        };
        "client.ClientResponse": {
            client_id?: string;
            client_name?: string;
            client_secret?: string;
            client_secret_expires_at?: number;
            client_type?: string;
            grant_types?: string[];
            redirect_uris?: string[];
            response_types?: string[];
            scopes?: string;
            token_endpoint_auth_method?: string;
        };
        "client.ClientUpdateRequest": {
            client_name?: string;
            grant_types?: string[];
            is_active?: boolean;
            redirect_uris?: string[];
            response_types?: string[];
            scopes?: string;
            token_endpoint_auth_method?: string;
        };
        "introspect.IntrospectRequest": {
            token?: string;
        };
        "introspect.IntrospectResponse": {
            /** @description Whether the token is valid (true or false). */
            active?: boolean;
            /** @description Intended audience for the token (e.g., the API). */
            aud?: string;
            /** @description Client ID for which the token was issued. */
            client_id?: string;
            error?: string;
            error_description?: string;
            /** @description Expiration time (Unix timestamp). */
            exp?: number;
            /** @description Issued-at time (Unix timestamp). */
            iat?: number;
            /** @description Unique identifier for the token. */
            jti?: string;
            /** @description Not-before time (Unix timestamp). */
            nbf?: number;
            /** @description Space-delimited list of scopes associated with the token. */
            scope?: string;
            /** @description The subject of the token (typically the user ID). */
            sub?: string;
            /** @description The type of the token (usually "bearer"). */
            token_type?: string;
            /** @description The username of the authenticated user. */
            username?: string;
        };
        "model.ApiError": {
            code?: number;
            message?: string;
        };
        "model.AuthErrorResponse": {
            error?: string;
            error_description?: string;
        };
        "model.JWK": {
            /** @description Algorithm (e.g., RS256) */
            alg?: string;
            /** @description Exponent (base64url-encoded) */
            e?: string;
            /** @description Key ID */
            kid?: string;
            /** @description Key Type (e.g., RSA) */
            kty?: string;
            /** @description Modulus (base64url-encoded) */
            n?: string;
            /** @description Public Key Use (e.g., sig) */
            use?: string;
        };
        "model.JWKSResponse": {
            keys?: components["schemas"]["model.JWK"][];
        };
        "model.WellKnownConfigResponse": {
            authorization_endpoint?: string;
            claims_supported?: string[];
            end_session_endpoint?: string;
            id_token_signing_alg_values_supported?: string[];
            issuer?: string;
            jwks_uri?: string;
            registration_endpoint?: string;
            response_types_supported?: string[];
            scopes_supported?: string[];
            subject_types_supported?: string[];
            token_endpoint?: string;
            token_endpoint_auth_methods_supported?: string[];
            userinfo_endpoint?: string;
        };
        "token.TokenResponse": {
            access_token?: string;
            expires_in?: number;
            refresh_token?: string;
            scope?: string;
            token_type?: string;
        };
        "user.UserCreateRequest": {
            email?: string;
            password?: string;
            /** @description optional role assignment */
            role?: string;
            username?: string;
        };
        "user.UserResponse": {
            createdAt?: string;
            email?: string;
            id?: string;
            role?: string;
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
