basePath: /
definitions:
  models.UserCreateRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.UserResponse:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Authentication service using Go standard library
  title: Autentico Microservice API
  version: "1.0"
paths:
  /create:
    post:
      consumes:
      - application/json
      description: Registers a new user in the system
      parameters:
      - description: User creation payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserResponse'
      summary: Create a new user
      tags:
      - auth
swagger: "2.0"
