basePath: /api/v1/
definitions:
  models.ApiError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.ApiUserResponse:
    properties:
      data:
        $ref: '#/definitions/models.UserResponse'
      error:
        $ref: '#/definitions/models.ApiError'
    type: object
  models.UserCreateRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.UserResponse:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Authentication and ABAC Authorization Microservice
  title: Autentico Microservice API
  version: "1.0"
paths:
  /create:
    post:
      consumes:
      - application/json
      description: Registers a new user in the system
      parameters:
      - description: User creation payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ApiUserResponse'
      summary: Create a new user
      tags:
      - auth
swagger: "2.0"
