name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Download golangci-lint binary
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b ./bin v2.1.5
      - name: Run golangci-lint
        run: ./bin/golangci-lint run ./...

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
      - name: Check formatting
        run: gofmt -l -e .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
      - name: Build project
        run: go build main.go

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./tests/... -v

  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download nancy
        run: |
          curl -L https://github.com/sonatype-nexus-community/nancy/releases/download/v0.0.44/nancy-linux.amd64-v0.0.44 -o /usr/local/bin/nancy
          chmod +x /usr/local/bin/nancy
      - name: Run nancy to check for vulnerabilities
        run: go list -json -deps ./... | nancy sleuth
